#Instructions to generate models: openapi-generator-cli generate -i country-api.yaml -g spring -o output/

openapi: 3.0.0
info:
  title: Country API
  version: 1.0.0
paths:
  /countries:
    get:
      summary: Retrieve all countries
      responses:
        '200':
          description: A list of countries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
  '/countries/{name}':
    get:
      summary: Retrieve details about a specific country
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details about the country
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryDetails'
components:
  schemas:
    Country:
      type: object
      properties:
        name:
          type: string
        flag:
          type: string
    CountryDetails:
      type: object
      properties:
        name:
          type: string
        population:
          type: integer
        capital:
          type: string
        flag:
          type: string
