name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm test -- --watchAll=false

  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: ./gradlew test

  build:
    needs: [ test-frontend, test-backend ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        working-directory: backend

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Backend
        run: ./gradlew build
        working-directory: backend

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: frontend

      - name: Build Frontend
        run: npm run build
        working-directory: frontend

      - name: Cleanup build artifacts
        run: |
          find backend -name '*plain.jar' -delete
          find backend -name '*source.jar' -delete
          find backend -name '*.javac.jar' -delete

      - name: Upload Backend JAR
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/build/libs/*.jar


  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dockerize Backend
        run: |
          docker build -t country-backend ./backend
      - name: Dockerize Frontend
        run: |
          docker build -t country-frontend ./frontend
